- name: Install EPEL.
  yum:
    name: epel-release
    state: latest

- name: Add the Docker CE repository.
  yum_repository:
    name: docker-ce
    description: Docker CE repository
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes

- name: Install the Docker GPG key.
  rpm_key:
    state: present
    key: https://download.docker.com/linux/centos/gpg

- name: Update the system.
  shell: "{{ item }}"
  with_items:
    - yum makecache fast -y
    - yum update -y

- name: "Install services: NTP, Kubernetes."
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - ntp
    - kubernetes
    - runc
  notify: Start the services.

- name: Add simple hosts for easy configuration.
  copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- block:
  - name: Disable or stop certain firewall services.
    service:
      name: "{{ item }}"
      state: stopped
    with_items:
      - iptables
      - firewalld
  rescue:
    - meta: flush_handlers
