- name: Install EPEL.
  yum:
    name: epel-release
    state: latest

- name: Install virt7 Docker Repo.
  yum_repository:
    name: virt7-docker-common-release
    baseurl: http://cbs.centos.org/repos/virt7-docker-common-release/x86_64/os/
    gpgcheck: no

- name: Disable SE Linux.
  shell: setenforce 0

- name: Update the system.
  shell: "{{ item }}"
  with_items:
    - yum makecache fast -y
    - yum update -y

- name: "Install services: NTP, Kubernetes."
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: virt7-docker-common-release
  with_items:
    - ntp
    - kubernetes
    - etcd
    - flannel
  notify: Start the services.

- name: Add simple hosts for easy configuration.
  copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- block:
  - name: Disable or stop certain firewall services.
    service:
      name: "{{ item }}"
      state: stopped
    with_items:
      - iptables
      - firewalld
  rescue:
    - meta: flush_handlers
