- name: Install needed configuration.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - kubernetes/config
    - kubernetes/kubelet

- name: debug
  debug: "msg={{ ansible_default_ipv4.address }}"