- name: Install needed configuration.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - kubernetes/config
    - kubernetes/kubelet

- name: Add the correct hostname to each kubelet.
  replace:
    dest: /etc/kubernetes/kubelet
    regexp: REPLACE_ME
    replace: "{{ item.name }}"
  when: item.ip == "{{ansible_default_ipv4.address | trim}}"
  with_items:
    - "{{ minions }}"

- name: Enable and start needed services.
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - kube-proxy
    - kubelet
    - docker