master_host: centos-master
listen_address: 0.0.0.0
minions:
  - name: centos-minion1
    ip: 172.31.22.181
  - name: centos-minion2
    ip: 172.31.23.178
  - name: centos-minion3
    ip: 172.31.18.252